[package]
name = "GameOfLifeRust"
version = "0.1.0"
authors = ["Tastaturtaste <joshua.moellers@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
