[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Tastaturtaste <joshua.moellers@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [profile.release]
# debug = true

[dependencies]
winit = "0.25.0"
pixels = "0.3.0"
rand = "0.8.3"
rayon = "1.5.0"